<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="Alex-NB" name="ua.goit.timonov.antMaven.module02.IntTaskTest" tests="8" failures="0" timestamp="24 Jun 2016 13:00:23 GMT" time="0.044" errors="0">
  <testcase name="testExecuteCatchForException_2" time="0.000" classname="ua.goit.timonov.antMaven.module02.IntTaskTest"/>
  <testcase name="testExecuteNormal_2" time="0.001" classname="ua.goit.timonov.antMaven.module02.IntTaskTest"/>
  <testcase name="testExecuteCatchForException_1" time="0.036" classname="ua.goit.timonov.antMaven.module02.IntTaskTest"/>
  <testcase name="testGetResultNormal_3" time="0.000" classname="ua.goit.timonov.antMaven.module02.IntTaskTest"/>
  <testcase name="testGetResultNormal_2" time="0.000" classname="ua.goit.timonov.antMaven.module02.IntTaskTest"/>
  <testcase name="testExecuteNormal_3" time="0.000" classname="ua.goit.timonov.antMaven.module02.IntTaskTest"/>
  <testcase name="testExecuteNormal_1" time="0.007" classname="ua.goit.timonov.antMaven.module02.IntTaskTest"/>
  <testcase name="testGetResultNormal_1" time="0.000" classname="ua.goit.timonov.antMaven.module02.IntTaskTest"/>
</testsuite> <!-- ua.goit.timonov.antMaven.module02.IntTaskTest -->
